CREATE OR REPLACE VIEW
PRODUCTS_STG_VIEW
AS SELECT
PRODUCT_ID, PRODUCT_NAME, PRODUCT_SKU, PRODUCT_DESCRIPTION
FROM PRODUCTS_STG
WHERE LINE_NUMBER
IN
(
SELECT MAX(LINE_NUMBER) AS LINE_NUMBER FROM PUBLIC.PRODUCTS_STG GROUP BY PRODUCT_ID
);