MERGE INTO PRODUCTS_FCT FCT
    USING(
        SELECT PRODUCT_ID,
               PRODUCT_NAME,
               PRODUCT_SKU,
               PRODUCT_DESCRIPTION,
        FROM PRODUCTS_PRUNE
    ) STG

ON( FCT.PRODUCT_ID = STG.PRODUCT_ID)

WHEN MATCHED THEN
    UPDATE SET
        FCT.PRODUCT_NAME = STG.PRODUCT_NAME,
        FCT.PRODUCT_DESCRIPTION = STG.PRODUCT_DESCRIPTION

WHEN NOT MATCHED THEN
    INSERT(
    PRODUCT_ID,
    PRODUCT_NAME,
    PRODUCT_SKU,
    PRODUCT_DESCRIPTION
    )
    VALUES(
    STG.PRODUCT_ID,
    STG.PRODUCT_NAME,
    STG.PRODUCT_SKU,
    STG.PRODUCT_DESCRIPTION
    )
;